title: "Judith Jeyafreeda Andrew"
theme: minima
markdown: kramdown
author:
  name: "Judith Jeyafreeda Andrew"
  email: "judithjeyafreeda@gmail.com"
description: "Clinical NLP • Temporal Reasoning • Trustworthy Medical AI"
